export default {
	ab: /^(?:$AB)(?!\p{L})/iu,
	and: /^(?:$AND|&)/i,
	c_explicit: /^[\s*]*(?:$CHAPTER)[\s*]*/i,
	c_sep_eu: /^\x1f\x1f\x1f/i,
	c_sep_us: /^\x1f\x1f\x1f/i,
	cv_sep_weak: /^(?:[\s*]*["'][\s*]*|[\s*])+/i,
	cv_sep_eu: /^[\s*]*,+[\s*]*/i,
	cv_sep_us: /^[\s*]*(?::+|\.(?!\s*\.\s*\.))[\s*]*/i,
	ff: /^[\s*]*(?:$FF)(?![\p{L}\p{N}])(?:\.(?!\s*\.))?/iu,
	in_book_of: /^[\s*]*(?:from|of|in)[\s*]*(?:the[\s*]*book[\s*]*of[\s*]*)?/i,
	next: /^(?:$NEXT)/i,
	ordinal: /^(?:th|st|nd|rd)/i,
	range: /^[\s*]*(?:[\-–—]|$TO)+[\s*]*/i,
	sequence_eu: /^(?:[;/:&\-–—~\s*]|\.(?!\s*\.\s*\.)|$AND)+/i,
	sequence_us: /^(?:[,;/:&\-–—~\s*]|\.(?!\s*\.\s*\.)|$AND)+/i,
	space: /^[\s*]+/,
	title: /^[\s*]*(?:$TITLE)(?!\p{L})[\s*]*/iu,
	v_explicit: /^[\s*]*(?:$VERSE)[\s*]*(?!\p{L})/iu
};